appVersion: 0.1
appName: PayGoGateway
config: ""
config:
  config:
    apiUrl: ""
    apiVersion: ""
    apiClientID: ""
    apiClientSecret: ""
    apiToken: ""
    charset:
  routes:
    accesstoken: "/oauth/token"
    customers:
      common: "/customers"
      search: "/customers/search"
    identificationType: "/identification_types"