appVersion: 0.1
appName: PayGoGateway
config: ""
config:
  config:
    apiUrl: "https://api.mercadopago.com"
    apiVersion: "v1"
    apiClientID: "your-client-id"
    apiClientSecret: "your-client-secret"
    apiPublicKey: "your-public-key"
    apiToken: "your-access-token"
    charset: "application/json;charset=utf-8"
  routes:
    accesstoken: "/oauth/token"
    customers:
      common: "/customers"
      search: "/customers/search"
    identificationType: "/identification_types"